version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/" # This should be / rather than .github/workflows
    schedule:
      interval: "daily"
    reviewers:
      - "oslokommune/kjoremiljo"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      all:
        patterns:
          - "*"
