name: "Tap and install ok with Homebrew"

on:

  workflow_dispatch:

jobs:

  homebrew:

    name: "Tap and install ok with Homebrew"

    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: Install ok
        run: |
          brew tap oslokommune/ok https://github.com/oslokommune/ok
          brew install ok
