name: "Tap and install ok with Homebrew"

on:

  workflow_dispatch:

jobs:

  homebrew:

    name: "Tap and install ok with Homebrew"

    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:

      - name: Load SSH deploy key
        uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e # v0.8.0
        with:
          ssh-private-key: ${{ secrets.OK_PRIVATE_DEPLOY_KEY }}


      - name: Install ok
        env:
          HOMEBREW_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          brew tap oslokommune/ok git@github.com:oslokommune/ok.git
          brew install ok
