name: Test installation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [fedora, ubuntu, archlinux]

    steps:

    - name: Checkout ⚙️
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7


    - name: Set up Docker Buildx ⚙️
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1


    - name: Build Docker image
      uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
      with:
        context: .
        file: Dockerfile.${{ matrix.dockerfile }}
        tags: ok-${{ matrix.dockerfile }}
        load: true
        push: false
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"

    - name: Test Docker image
      run: docker run --rm ok-${{ matrix.dockerfile }}
